version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bibliotheque-db
    environment:
      POSTGRES_DB: bibliotheque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Benthe@2001
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./bibliotheque-backend
      dockerfile: Dockerfile
    container_name: bibliotheque-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bibliotheque
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Benthe@2001
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./bibliotheque-frontend
      dockerfile: Dockerfile
    container_name: bibliotheque-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data: